Cadena_Favores/config/routes.rb
Rails.application.routes.draw do
  get '/' => "chains#landing", as: "root"
  get '/chains/map' => "chains#map", as: 'map'
  get '/chains/info' => "chains#info", as: 'info'
  get '/chains/chart' => "chains#chart", as: 'chart'
  get '/chains/new' => "chains#new", as: 'new'
  get '/chains' => "chains#index" 


  resources :chains do
    resources :userposts
  end 
end

Cadena_Favores/app/models/chain.rb
class Chain < ActiveRecord::Base
	has_many :userposts
end

Cadena_Favores/app/models/userpost.rb
class Userpost < ActiveRecord::Base
	belongs_to :chain
	  
end

Cadena_Favores/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
end

Cadena_Favores/app/controllers/chains_controller.rb
class ChainsController < ApplicationController
	def index
		@chains = Chain.all
		@chain = Chain.find 1
		@user_posts = @chain.userposts

		@userposts = []

		@chains.each do |chain|
			@userposts.push chain.userposts
		end

		respond_to do |format|
			format.html
			format.json { render json: @userposts }
		end
	end

	def show
		@chain = Chain.find params[:id]	

	end

	def landing
	end

	def new
		@chain = Chain.new
	end

	def create
		
		@chain_params = params[:newChain]
		@chain = Chain.new
		@chain.name = @chain_params["name"]
		@chain.date_chain = @chain_params["date"]
		@chain.description_chain = @chain_params["description"]

		if @chain.save
			respond_to do |format|
				format.html
				format.json { render json: 1 }
			end
		else
			render 'index'
		end
	end

	def destroy
		@chain = Chain.find(params[:chain_id])
		chain.destroy
		redirect_to '/chains'	
	end



	private

	def chain_params
		params.require(:chain).permit(:name, :date_chain, :description_chain)
	end


end

Cadena_Favores/app/controllers/userposts_controller.rb
class UserpostsController < ApplicationController
	def index
		@chain = Chain.find(params[:chain_id])
		@userposts = @chain.userposts
	end

	def create	
		comment = params[:comment]
		user = params[:user]
		address = params[:city]

		chain = Chain.find(params[:chain_id])
		chain.userposts.create comment: comment, user: user, address: address

		render json: 1
	end

	

	def map
		@user_posts= Userpost.select(:address)
		render "map", layout: false
		
	end
end

Cadena_Favores/app/helpers/application_helper.rb
module ApplicationHelper
end

Cadena_Favores/app/helpers/chains_helper.rb
module ChainsHelper
end

Cadena_Favores/app/helpers/userposts_helper.rb
module UserpostsHelper
end

Cadena_Favores/app/views/chains/chart.html.erb
<%= geo_chart Medal.group(:country).count %>
<%= line_chart completed_tasks_charts_path %>

Cadena_Favores/app/views/chains/index.html.erb
<img src="../images/hands.jpg" class="hands">

<div class="big-tab">
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
  	<% @chains.each do |chain| %>
   	<li role="presentation" class=""><a href="#<%= chain.id %>" aria-controls="<%= chain.id %>" role="tab" data-toggle="tab"><%= chain.name %></a></li>    
  <% end %>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
	  	<% @chains.each do |chain| %><br>
	      <div role="tabpanel" class="tab-pane" id="<%= chain.id %>">
	 			<% chain.userposts.each do |userpost| %>
					<div class="container">
				      <ul class="timeline">
				        <li>
				          <div class="timeline-badge up"><i class="fa fa-thumbs-up"></i></div>
					          <div class="timeline-panel timeline-width">
					            <div class="timeline-heading">
					              <h4 class="timeline-title">User: <%= userpost.user %></h4>
					            </div>
					            <div class="timeline-body">
					              <p>Comment: <%= userpost.comment %></p>
					              <p>City: <%= userpost.address %></p>

					            </div>
					          </div>
				        </li>
				      </ul>
					</div>
				<% end %>	
				<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
				CREATE A NEW POST
				</button>
				<div class="modal fade" id="myModal">
	  				<div class="modal-dialog">
	    				<div class="modal-content">
	      				<div class="modal-header">
	        					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        					<h4 class="modal-title">Modal title</h4>
	      				</div>
	      				<div class="modal-body">
	      					Name: <input type="text" name="<%= chain.id %>" id="user-field"><br>
  								Put here your experience: <textarea form ="testformid" name="<%= chain.id %>" id="comment-field" cols="35" wrap="soft"></textarea><br>
  								City: <input type="text" name="<%= chain.id %>" id="city-field"><br>
  								Save: <input type="submit" name="<%= chain.id %>" id="btn-send">
	      				</div>
	     				</div><!-- /.modal-content -->
	    			</div><!-- /.modal-dialog -->
	  			</div><!-- /.modal -->	
			</div>
		<%end%>
	</div>

 </div>

<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal2">
CREATE A NEW CHAIN
</button>

<div class="modal fade" id="myModal2">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">NEW CHAIN</h4>
      </div>
      <div class="modal-body">
      
    	Name: <input type="text" name="" id="name-field"><br>
      Date: <input type="date" name="" id="date-field"><br>
      Description: <textarea form ="testformid" name="" id="description-field" cols="35" wrap="soft"></textarea><br>
      Save: <input type="submit" name="" id="button-send">     
      </div>
      


    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->

</div><!-- /.modal -->

Cadena_Favores/app/views/chains/info.html.erb
<div class="container photos">
  <div class="row">

            <div class="col-md-3">
              <div class="thumbnail">
                <img src="pulmones.jpg" >
                  <div class="caption">
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                
              </div>
            </div>
          </div>

          <div class="col-md-3">
            <div class="thumbnail">
              <img src="arbol.jpg">
              <div class="caption">
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                </div>
            </div>
          </div>


          <div class="col-md-3">
            <div class="thumbnail">
              <img src="foto3.jpg">
              <div class="caption">
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                </div>
              
            </div>
            </div>
  </div>
</div>

Cadena_Favores/app/views/chains/landing.html.erb
<div class="background">
<img src="../images/roots.jpg">
</div>

<div class="container-photos">
  <div class="row">

            <div class="col-md-3">
                <img src="../images/Hands2.png" class= "hands_icon">
                  <div class="caption">    
                  <h3>Find the purpose.</h3>
                  <h4>All day there are many people who need your help.
                    Unfortunately, to do that you don't need to go so far.
                    Only you have to see what is whappening around you </h4>
                  </div>
            </div>
          <div class="col-md-3">            
              <img src="../images/Hands3.png" class="hands_icon2">
              <div class="caption">
                  <h3>Help others with a small act of kindness.</h3>
                  <h4>Small acts for big people. It doesn't matter what kind of favor you want to do, only your determination and good purpose.<h4>
                </div>         
          </div>
          <div class="col-md-3">   
              <img src="../images/Hands4.png" class="hands_icon3">
              <div class="caption">
                  <h3>Share your experience!.</h3>
                  <h4>Once that you have received a favour it is your turn to share and to promote the idea. Tell us and all these comunity your experience and keep growing the roots!</h4>
                </div>
          </div>
          <div class="twitter col-md-3">
            <a class="twitter-timeline" href="https://twitter.com/notipositivas" data-widget-id="615916771074265088">Tweets por el @notipositivas.</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
            </script>
          </div>

  </div>
</div>


<section class="video">
   
    <a href="javascript:void(0);" class= "video-play" title="Clic para ver el video" onclick="window.open('http://www.youtube.com/v/36UWY92ub8c&autoplay=1', 'sickg', 'left=390, top=200, width=435, height=354, toolbar=0, resizable=1')"><div align="center"><span class= "glyphicon glyphicon-play-circle play"></span></div></a>
    <img src="../images/act.jpg" alt="" class="video_foto"/>
    
</section>

Cadena_Favores/app/views/chains/map.html.erb
<img src= "../images/people.jpg" class="people">
<div id="map-canvas" style="width: 765px; height: 388px"></div>
<style type="text/css">
			#map {
				width: 400px;
				height: 400px;
			}
</style>
<img src= "../images/people.jpg" class="people2">





    
    	

<!--
		<div id="map"></div>
		<script>
			var db = ["Barcelona","Madrid"]
			var map = new GMaps({
				el: '#map',
				lat: -12.043333,
				lng: -77.028333
			});

		$("#btn-search").on('click', function(){
			for(var i =0; i < db.length; i++) {
			 GMaps.geocode({
			  address: db[i],
			  callback: function(results, status) {
			    if (status == 'OK') {
			      var latlng = results[0].geometry.location;
			      map.setCenter(latlng.lat(), latlng.lng());
			      map.setZoom(16);
			      map.addMarker({
			        lat: latlng.lat(),
			        lng: latlng.lng()
			      });
			    }
			  }
			 });
			}
		})
		</script>-->

Cadena_Favores/app/views/chains/new.html.erb
<%= form_for @chain do |f| %>
<div>
 <%= f.label :name %>
 <%= f.text_field :name %>
 </div>

 <div>
 <%= f.label :date_chain %>
 <%= f.date_field :date_chain %>
</div>
<div>
 <%= f.label :description_chain %>
 <%= f.text_field :description_chain %>
 </div>

 <%= f.submit 'Save' %>

<% end %>

Cadena_Favores/app/views/chains/show.html.erb
<%= @chain.name %>

<%= @chain.date_chain %>
<%= @chain.description_chain %>
 

Cadena_Favores/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>PROYECTO</title>
	  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
		
	  
	  <%= stylesheet_link_tag    'application', media: 'all' %>
	  <%= javascript_include_tag 'application' %>
	  
	  
	  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
 	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
	  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
	

	
	</head>	
				
	<body>
			<header>
				<%= link_to 'ENDLESS RIPPLE', root_path %>
				<span class="btn-group-pull-right">
		            <%= link_to'Info', info_path %>
		            <%= link_to 'Chains', chains_path %>
		            <%= link_to 'Map', map_path %>
		            
		 		</span>
			</header>



		
		<%= yield %>	
		<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
		
		
		
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

		<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script>
		
	

		

		
    	<footer> 
			<hr> Created by Irene Muñoz Real ® Ironhack 2015 </hr>
		</footer>
	</body>
</html>